### ISSUE TITLE
Neue Rollen

### ISSUE THREAD

**Issue by YunesBaccouche** [walamana/werwolf-telegram#18]
Der Polizistenwerwolf
Er hat zwei Mal im Spiel die Möglichkeit Fake Beweise über die Spielleitung zu diskutieren.

Der Würfler
Darf pro Tag einmal würfeln. Würfelt er richtig erfährt er die Rolle eines beliebigen Spielers.

**Comment by walamana** [comment]
Den Polizistenwolf check i ned ganz. 

Und den Würfler find ich ganz doof

**Comment by walamana** [comment]
Der Würfler:
- Stärke: 3
- Würfelt jeden Tag: Wenn richtig -> Rolle einer Person; Max. 2 mal eine Person aufgedeckt
