### ISSUE TITLE
Neue Rolle: Der Viruspatient / Der Ischgler

### ISSUE THREAD

**Issue by walamana** [walamana/werwolf-telegram#19]
Entwurf, noch ausbaufähig: 
Aggiert als eigene Gruppe. Sein Ziel ist es die ganze lebende Bevölkerung zu infizieren, bevor die infizierte Person stirbt.
1. Nacht: Infiziert 2 Personen
Jede weitere Nacht: eine weitere Person.
-> Die werden mit Viruspatient in eine Gruppe hinzugefügt, in der sie aber nicht schreiben können

**Comment by Mag162** [comment]
Ich würde es hochschrauben: Sein Ziel ist es, dass alle lebenden Mitspieler infiziert sind.

**Comment by Mag162** [comment]
Der Viruspatient aus Ischgl
Sein Ziel ist es, alle Mitspieler (Werwölfe und Dorfbewohner) mit seinem Virus zu infizieren. Er gewinnt sobald alle lebenden Spieler von ihm infiziert worden sind. In der ersten Nacht darf er zwei Personen infizieren, in allen anderen Nächten eine weitere. Alle infizierten Spieler behalten ihre Rolle und ihre Sonderfähigkeiten. Alle Infizierten kommen in die Infiziertengruppe. In dieser Gruppe darf nicht geschrieben werden, sie dient nur der Information, wer bereits infiziert wurde. Stirbt der Viruspatient kann er nicht mehr gewinnen. Einen Schutz vor einer Infektion gibt es nicht.
