### ISSUE TITLE
Dorfschlampen/Bürgermeister Konflikt

### ISSUE THREAD

**Issue by YunesBaccouche** [walamana/werwolf-telegram#31]
Sehr unwahrscheinlicher Fall, dass die Dorfschlampe zur Bürgermeisterin wird. 

Aber gilt der Bürgermeisterschutz dann auch für ihre eigene Übernachtung?

**Comment by walamana** [comment]
@YunesBaccouche Ich würd sagen, da es sich ja dann bei einer Übernachtung bei einem Werwolf um einen Werwolfangriff handelt, und der Bürgermeister davor geschützt ist, gilt der Schutz auch hier.
