### ISSUE TITLE
Dokumentation für das Regelwerk

### ISSUE THREAD

**Issue by walamana** [walamana/werwolf-telegram#7]
Es braucht unbedingt noch eine Dokumentation für das Regelwerk:
- Wie erstelle ich neue Rollen?
- Wie ändere ich etwas an der Textvorlage?
- Wie nutze ich Variablen in meinem Text?
- ...

**Comment by YunesBaccouche** [comment]
Warum willst du eine Dokumentation einbauen? @walamana

**Comment by walamana** [comment]
Eigentlich vor allem hier für das Repository, 
z.B. [Wikieinträge](https://github.com/walamana/werwolf-telegram/wiki), Erklärungen, Spielleitertipps

**Comment by YunesBaccouche** [comment]
OK, aber wäre es nicht allgemein sinnvoller, wenn wir auf Englisch kommunizieren sollten?

**Comment by walamana** [comment]
Vielleicht tatsächlich. Aber Ich glaub, dass no ned so viele Englische Leute des lesen werden xD . Ich schätz, dass des primär an deutschsprachige kommen wird, Zumal ist ja unser Regelwerk auch auf Deutsch.

Was möglich wäre, ist, dass man im Einleitungstext hier auf Github eine kurze Englische Erklärung macht, und wenn sich jemand findet, der des auf Englisch auch gerne hätte, dann kann man mit dem ja mal zusammen arbeiten und alles auf Englisch verfassen.

**Comment by walamana** [comment]
Aber es wär definitv bei den technischen Sachen leichter, weil deutsche Begriffe aus der Informatik zu finden gar ned so leicht is xD

**Comment by YunesBaccouche** [comment]
Das Ganze ist für mich eh schon sehr undurchsichtig und jetzt bin ich doch zu einem Mindestmaß versiert.

**Comment by walamana** [comment]
Gut, dann müsst ma des vll mal zusammen besprechen, dass es so geschrieben is, dass es alle verstehen 😬

**Comment by lupilulu** [comment]
Ja ist vielleicht garnicht schlecht, weil alles raff ich auch noch nicht

**Comment by walamana** [comment]
@YunesBaccouche @lupilulu soll ma des zusammen mal machen? Dann assign ich des an uns

**Comment by YunesBaccouche** [comment]
Ich weiß nicht so recht, was mir da ne Beschäftigung mit den Fachbegriffen und so bringen soll. Programmieren und Coden war nie so meins...

**Comment by walamana** [comment]
Da gängs eher um Konfiguration etc. . Wenn des andere hernehmen wollen würden, müsste des vll in so einfacher Sprache gestaltet sein, dass man nur Konfigurationsdateien ändern muss.
Ich glaub, wenn des ned nur ich mach, dann würden eben so Fachbegriffe auch rausfallen, dies vll. gar nicht braucht.
Was z.B. wichtig ist, ist, wie man in der Konfigurationsdatei eine neue Rolle erstellt, oder, wie man in der Regelwerkvorlage neue Abschnitte einfügt. Sind ja alles im Endeffekt leichte Textdateien

**Comment by lupilulu** [comment]
Meins wird's wahrscheinlich nie sein, aber er kann uns ja trotzdem einfach Mal zeigen wie des gemacht wird jetzt speziell zb wie man eine Rolle erstellt weil dann könnten wir des ja auch Mal machen wenn's is, so schwer wird des schon nicht sein

**Comment by Gergely1302** [comment]
Servus beinand.
